name: Publish package to NPM

# Good article: https://medium.com/@codewithwaheed/publish-your-first-package-using-npm-and-github-actions-e453ca9f9fd2

on:
    push:
        branches: master

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
                  registry-url: 'https://registry.npmjs.org/'
            - run: npm install
            - run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
